/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

public class GitHubGreeter {

  public String welcome(String name){
    // Uncomment line below...
    // return "Welcome to GitHub, " + name;
  }

public String wishes(){
  // Uncomment line below...
  // return "I hope you enjoy the class!";
  }

}
