/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GitHubGreeterTest {

    @Test
    void instantiation() {
        // Check that the greeter object can be instantiated
        GitHubGreeter gg = new GitHubGreeter();
        assertNotNull(gg, "Could not instantiate greeter");
    }

    @Test
    void testWelcome() {
// Test the welcome String
        String expected = "Welcome to GitHub, James.";
        GitHubGreeter gg = new GitHubGreeter();
        String actual = gg.welcome("James");
        assertEquals(expected,actual);
    }

    @Test
    void testWishes() {
// Test the welcome String
        String expected = "I hope you enjoy the class!";
        GitHubGreeter gg = new GitHubGreeter();
        String actual = gg.wishes();
        assertEquals(expected,actual);
    }

}
